Repository ElenjaM/welcome-hsb-back, pull requests merged in 2025-05, with the labels that each got.

#9 Datenbank
  package-lock.json
  package.json
  src/app.js
  src/backup/app.js
  src/server.js
  src/services(DB)/DB_connection.js
  src/services(DB)/SQL_Abfrage.js
  src/services(DB)/welcome@HSB_DB.sql
Labels: database

#10 Added git manual
  git_manual/Github-Prozeduren-Befehle.md
  git_manual/image-1.png
  git_manual/image-10.png
  git_manual/image-11.png
  git_manual/image-12.png
  git_manual/image-13.png
  git_manual/image-14.png
  git_manual/image-15.png
  git_manual/image-16.png
  git_manual/image-17.png
  git_manual/image-2.png
  git_manual/image-3.png
  git_manual/image-4.png
  git_manual/image-5.png
  git_manual/image-6.png
  git_manual/image-7.png
  git_manual/image-8.png
  git_manual/image-9.png
  git_manual/image.png
Labels: documentation

#13 5 api endpunkte
  MySQL/app.js
  MySQL/controllers/benutzer.controller.js
  MySQL/controllers/gebaeude.controller.js
  MySQL/controllers/hochschulangehoerige.controller.js
  MySQL/controllers/organisationsbereich.controller.js
  MySQL/controllers/raum.controller.js
  MySQL/controllers/raumnutzung.controller.js
  MySQL/controllers/veranstaltung.controller.js
  MySQL/models/benutzer.model.js
  MySQL/models/gebaeude.model.js
  MySQL/models/hochschulangehoerige.model.js
  MySQL/models/organisationsbereich.model.js
  MySQL/models/raum.model.js
  MySQL/models/raumnutzung.model.js
  MySQL/models/veranstaltung.model.js
  MySQL/routes/benutzer.routes.js
  MySQL/routes/gebaeude.routes.js
  MySQL/routes/hochschulangehoerige.routes.js
  MySQL/routes/organisationsbereich.routes.js
  MySQL/routes/raum.routes.js
  MySQL/routes/raumnutzung.routes.js
  MySQL/routes/veranstaltung.route.js
  package-lock.json
  package.json
Labels: api
